name: Update Docker Hub Description

on:
  # run it on push to the default repository branch
  push:
    branches: [main]
    paths:
      - 'README.md'

jobs:
  dockerHubDescription:
    name: Update Description on DockerHub
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update dockerhub repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: snorre0815/mobility-print
          short-description: ${{ github.event.repository.description }}

